### ISSUE TITLE
SyntaxError: invalid syntax (Python 2.7.12)

### ISSUE THREAD

**Issue by ShaiMagal** [bramton/degiro#12]
Not working:

root@home:/tmp# python a.py
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from degiro import degiro
  File "/tmp/degiro.py", line 12
    def login(self, conf_path=None, with2fa:bool=False):
                                           ^
SyntaxError: invalid syntax

**Comment by bramton** [comment]
Python 2.7 is not supported for this API. Try to use a more recent version of Python, such as 3.6 or 3.7.
