### ISSUE TITLE
How do intercept /update calls and the likes ?

### ISSUE THREAD

**Issue by AdrienHorgnies** [bramton/degiro#14]
Hi,

I hope you don't mind I use this issue to ask information.

When I check my browser network console, I don't see calls such as `https://trader.degiro.nl/trading/secure/v5/update/`. How do you know about them ?

Thanks

**Comment by bramton** [comment]
Hi Adrien,

On my Firefox network console the calls do show up. Are you sure your are not filtering the incorrect calls ? They should be XHR calls. Perhaps forgot to reload the page after enabling the network console ?

Cheers, Bram

**Comment by AdrienHorgnies** [comment]
I checked with a different browser and a different computer and still don't see the call T_T. Well, I'm achieving my goal by reading other repositories.

Thank you

**Comment by AdrienHorgnies** [comment]
By the way, I could finally intercept the calls using a proxy (Fiddler Everywhere).
