### ISSUE TITLE
Get Transactions overview - Status Code 400

### ISSUE THREAD

**Issue by justinzweep** [bramton/degiro#16]
Hi, thanks for making this.

For me the getTransactions doesn't work I get a 400. Did degiro shut down this route or is it me messing up somewhere?

**Comment by Chavithra** [comment]
Hi,

**Answer**
the request sent from the method `getTransactions` of this library seems to be the right one : so it should work.

Is it possible to see which parameters you used to call this function ?

**Library**
This library no longer seems to be maintained : the last update (except for the License) was 10 months ago.

If you are looking for an alternative I made one : 

https://github.com/Chavithra/degiro-connector

It is documented and I plan to maintain it for a while.
