### ISSUE TITLE
product instead of id

### ISSUE THREAD

**Issue by premier-lifeboat** [bramton/degiro#2]
Hi
would it be possible to provide the product (having a understandable name) rather than the strage id values?

Regards, Armin

**Comment by bramton** [comment]
It is possible to get the product names, I'll have a look at it during the Easter holiday.

There seem to be two methods to get the product names, first is a POST with a JSON array of product ids.
https://trader.degiro.nl/product_search/secure/v5/products/info?intAccount=xxxxxx&sessionId=xxxxx.prod2
This will return slightly abbreviated versions of full names.
e.g. ISHARES B E CORP

Second is a POST/GET combination to https://degiro.quotecast.vwdservices.com
It requires the vwdid of products. It will return real full names of products.
e.g. iShares Core Euro Corporate Bond

I'll try to implement the first option as it is a lot easier.

**Comment by bramton** [comment]
I just made a commit which provides product names as well. Each product has a lot more of data available now, like ISIN and close price. Have a look at the updated README how to use the updated API.

**Comment by premier-lifeboat** [comment]
just got noticed by you closing the issue - your change works perfect for me. Thanks a lot

**Comment by wuhkuh** [comment]
First of all, thanks for this library! I have one question to which you seem to know the answer.

> Second is a POST/GET combination to https://degiro.quotecast.vwdservices.com
> It requires the vwdid of products. It will return real full names of products.
> e.g. iShares Core Euro Corporate Bond

I'm looking to implement this function, and also a way to neatly get the vwdids from quotecast; however I can't find any examples in any available documentation on the matter at this moment. I've seen calls to the API of the broker to get the vwdids, but I'd rather limit my dependencies to just quotecast for the data acquisition part.

Essentually what it boils down to is what the API expects for the POST method in terms of URL, headers and body (assuming the GET request is the same for any call to the API; just the [url]/[session]). Could you give me a push in the right direction?

For the name, could the POST request have a body looking like ```{"controlData": "req([vwdid].Name);"}``` by chance?

**Edit**
To get a full name from quotecast, use the field dubbed FullName. I'm still unsure how to fetch all vwdids and map them to a product.
