### ISSUE TITLE
Unused local variable header in login()

### ISSUE THREAD

**Issue by chmike** [bramton/degiro#6]
At line 21, you have the instruction :

``` Python
header={'content-type': 'application/json'}
```    
But this variable is never used.

You then have the instruction:

``` Python
r = self.sess.post(url, data=json.dumps(payload))
```

Shouldn't it be :

``` Python
r = self.sess.post(url, headers=header, data=json.dumps(payload))
```

Or something like that ?

**Comment by chmike** [comment]
Another possibility could be to write

``` Python
self.sess.headers.update({'content-type': 'application/json'})
```

Which would ensure that every request has this header.

**Comment by bramton** [comment]
Well spoted :+1: It has been resolved now.
